SELECT
  t001.MANDT AS Client_MANDT,
  t001.WAERS AS CurrencyCode_WAERS,
  t001.BUKRS AS CompanyCode_BUKRS,
  t001.BUTXT AS CompanyText_BUTXT,
  t001.ORT01 AS CityName_ORT01,
  t001.LAND1 AS Country_LAND1,
  t001.SPRAS AS Language_SPRAS,
  t001.KTOPL AS ChartOfAccounts_KTOPL,
  t001.PERIV AS FiscalyearVariant_PERIV,
  t001.RCOMP AS Company_RCOMP,
  t001.KKBER AS CreditControlArea_KKBER,
  t001.KTOP2 AS CountryChartofAccounts_KTOP2,
  t001.FIKRS AS FundsManagement_FIKRS
-- t001.WAABW AS MaximumExchangeRateDeviation_WAABW,
-- t001.KOKFI AS AllocationIndicator_KOKFI,
-- t001.ADRNR AS Address_ADRNR,
-- t001.STCEG AS VATRegistrationNumber_STCEG,
-- t001.XFMCO AS ProjectCashManagementIndicator_XFMCO,
-- t001.XFMCB AS CashBudgetManagementActiveIndicator_XFMCB,
-- t001.XFMCA AS ActivateUpdateInFundsManagement_XFMCA,
-- t001.TXJCD AS JurisdictionForTaxCalculation_TXJCD,
-- t001.FMHRDATE AS FundsCenterAssignedAccountHR_FMHRDATE,
-- t001.BUVAR AS CompanyCodeVariantScreen_BUVAR,
-- t001.FDBUK AS CashManagementForecastCompanyCode_FDBUK,
-- t001.XFDIS AS CashManagementActivatedIndicator_XFDIS,
-- t001.XVALV AS ProposeCurrentDateValueDateIndicator_XVALV,
-- t001.XSKFN AS DiscountBaseAmountNetValueIndicator_XSKFN,
-- t001.XMWSN AS BaseAmountTaxNetDiscountIndicator_XMWSN,
-- t001.MREGL AS RulesCopyingfromSampleAccountGLAccounts_MREGL,
-- t001.XGSBE AS BusinessAreaFinancialStatementsRequiredIndicator_XGSBE,
-- t001.XGJRV AS ProposeFiscalYearIndicator_XGJRV,
-- t001.XKDFT AS PostTranslationsExchangeRateDifferences_XKDFT,
-- t001.XPROD AS ProductiveCompanyCodeIndicator_XPROD,
-- t001.XEINK AS PurchaseAccountProcessingActiveIndicator_XEINK,
-- t001.XJVAA AS JVAActiveIndicator_XJVAA,
-- t001.XVVWA AS FinancialAssetsManagementActiveIndicator_XVVWA,
-- t001.XSLTA AS NoExRateDifferenceClearingLocalCrcy_XSLTA,
-- t001.XFDMM AS UpdatingMMCashMgmtForecastActivatedIndicator_XFDMM,
-- t001.XFDSD AS UpdatingSDCashMgmtForecastActivatedIndicator_XFDSD,
-- t001.XEXTB AS CompanyCodeInAnotherSystemIndicator_XEXTB,
-- t001.EBUKR AS OriginalKeyCompanyCode_EBUKR,
-- t001.UMKRS AS SalesPurchasesTaxGroup_UMKRS,
-- t001.BUKRS_GLOB AS NameofGlobalCompanyCode_BUKRS_GLOB,
-- t001.FSTVA AS FieldStatusVariant_FSTVA,
-- t001.OPVAR AS PostingPeriodVariant_OPVAR,
-- t001.XCOVR AS HedgeRequestActiveIndicator_XCOVR,
-- t001.TXKRS AS ForeignCurrencyTranslationTaxItems_TXKRS,
-- t001.WFVAR AS WorkflowVariant_WFVAR,
-- t001.XBBBF AS GLAccountAuthorizationCheckInventoryManagement_XBBBF,
-- t001.XBBBE AS GLAccountAuthorizationCheckPOSchedulingAgreement_XBBBE,
-- t001.XBBBA AS GLAccountAuthorizationCheckPurchaseRequisitions_XBBBA,
-- t001.XBBKO AS GLAccountAuthorizationCheckContracts_XBBKO,
-- t001.XSTDT AS DocumentDateasBasisTaxDeterminationIndicator_XSTDT,
-- t001.MWSKV AS InputTaxCodeNonTaxableTransactions_MWSKV,
-- t001.MWSKA AS OutputTaxCodeNonTaxableTransactions_MWSKA,
-- t001.IMPDA AS ForeignTradeImportDataControlMMPurchaseOrders_IMPDA,
-- t001.XNEGP AS NegativePostingsPermittedIndicator_XNEGP,
-- t001.XKKBI AS CreditControlAreaOverwrittenIndicator_XKKBI,
-- t001.WT_NEWWT AS ExtendedWithholdingTaxActive_WT_NEWWT,
-- t001.PP_PDATE AS ProcedureforSettingPostingDate_PP_PDATE,
-- t001.INFMT AS InflationMethod_INFMT,
-- t001.FSTVARE AS FundsReservationFieldStatusVar_FSTVARE,
-- t001.KOPIM AS ForeignTradeImportDataCopyingControlGR_KOPIM,
-- t001.DKWEG AS ForeignTradeScreenCtrlImpDatafMMGoodsReceipt,
-- t001.OFFSACCT AS MethodOffsettingAccountDetermination_OFFSACCCT,
-- t001.BAPOVAR AS AdditionalSettingsVariantForBusAreaFinancialStatements_BAPOVAR,
-- t001.XCOS AS CostofSalesAccountingStatus_XCOS,
-- t001.XCESSION AS AccountsReceivablePledgingActive_XCESSION,
-- t001.XSPLT AS EnableAmountSplit_XSPLT,
-- t001.SURCCM AS SurchargeCalculationMethod_SURCCM,
-- t001.DTPROV AS DocumentTypeProvisionsforTaxesonServicesReceived_DTPROV,
-- t001.DTAMTC AS DocumentTypeforJournalVoucherAmountCorrection_DTAMTC,
-- t001.DTTAXC AS DocumentTypeforJournalVoucherTaxCodeCorrection_DTTAXC,
-- t001.DTTDSP AS DocumentTypeforRemittanceChallans_DTTDSP,
-- t001.DTAXR AS DeferredTaxRule_DTAXR,
-- t001.XVATDATE AS TaxReportingDateActiveinDocuments_XVATDATE,
-- t001.PST_PER_VAR AS ManageVariantofPostingPeriodforCompanyCodeLedger_PST_PER_VAR,
-- t001.XBBSC AS GLAccountAuthorizationCheckInShoppingCart_XBBSC,
-- t001.F_OBSOLETE AS HideEntryinValueHelp_F_OBSOLETE,
-- t001.FM_DERIVE_ACC AS ActivateAccountAssignmentDerivationFundsManagement_FM_DERIVE_ACC
FROM
  `{{ project_id_src }}.{{ dataset_cdc_processed_s4 }}.t001` AS t001
