SELECT
  mcha.Mandt AS Client_Mandt,
  mcha.MATNR AS MaterialNumber_MATNR,
  mcha.CHARG AS BatchNumber_CHARG,
  mcha.WERKS AS Plant_WERKS,
  mcha.ERSDA AS CreationDate_ERSDA,
  mcha.ERNAM AS NameofPersonWhoCreatedtheObject_ERNAM,
  mcha.AENAM AS NameOfPersonWhoChangedObject_AENAM,
  mcha.LAEDA AS DateofLastChange_LAEDA,
  mcha.VERAB AS AvailabilityDate_VERAB,
  mcha.VFDAT AS ShelfLifeExpiration_VFDAT,
  mcha.HSDAT AS DateOfManufacture_HSDAT,
  mcha.ZUSCH AS BatchStatusKey_ZUSCH,
  mcha.ZUSTD AS BatchInRestricted_UseStock_ZUSTD,
  mcha.ZAEDT AS DateOfLastStatusChange_ZAEDT
-- mcha.LVORM AS DeletionFlagforAllDataOnABatchAtAPlant_LVORM,
-- mcha.LIFNR AS VendorsAccountNumber_LIFNR,
-- mcha.LICHA AS VendorBatchNumber_LICHA,
-- mcha.VLCHA AS OrginalBatchNumber_Deactivated_VLCHA,
-- mcha.VLWRK AS OrginalPlant_Deactivated_VLWRK,
-- mcha.VLMAT AS OriginalMaterial_Deactivated_VLMAT,
-- mcha.BWTAR AS ValuationType_BWTAR,
-- mcha.CHAME AS UnitOfIssueForBatch_Deactivated_CHAME,
-- mcha.LWEDT AS DateofLastGoodsReceipt_LWEDT,
-- mcha.FVDT1 AS DateForFreeUse1_FVDT1,
-- mcha.FVDT2 AS DateForFreeUse1_FVDT2,
-- mcha.FVDT3 AS DateForFreeUse1_FVDT3,
-- mcha.FVDT4 AS DateForFreeUse1_FVDT4,
-- mcha.FVDT5 AS DateForFreeUse1_FVDT5,
-- mcha.FVDT6 AS DateForFreeUse1_FVDT6,
-- mcha.HERKL AS CountryOfOriginOfMaterial_HERKL,
-- mcha.HERKR AS RegionOfOriginOfMaterial_HERKR,
-- mcha.MTVER AS MaterialGroupExportForForeignTrade_MTVER,
-- mcha.QNDAT AS NextInspectionDate_QNDAT,
-- mcha.CUOBJ_BM AS InternalObjNumber_BatchClassificationNumber_CUOBJ_BM,
-- mcha.DEACT_BM AS BatchIsNoLongerActive_DEACT_BM,
-- mcha.BATCH_TYPE AS TypeOfBatch_BATCH_TYPE ,
-- mcha.SGT_SCAT AS StockSegment_SGT_SCAT,
-- mcha.ERSDA_TMSTP AS Timestamp_ERSDA_TMSTP,
-- mcha.ERSDA_TZ_SYS AS TimeZone1_ERSDA_TZ_SYS,
-- mcha.ERSDA_TZ_USR AS TimeZone1_ERSDA_TZ_USR,
-- mcha.ZFDAT AS CertificationDate_ZFDAT,
-- mcha.FSH_SEASON_YEAR AS SeasonYear_FSH_SEASON_YEAR,
-- mcha.FSH_SEASON AS Season_FSH_SEASON,
-- mcha.FSH_COLLECTION AS FashionCollection_FSH_COLLECTION,
-- mcha.FSH_THEME AS FashionTheme_fsh_theme
FROM `{{ project_id_src }}.{{ dataset_cdc_processed_ecc }}.mcha` AS mcha
