SELECT
  t161.MANDT AS Client_MANDT,
  t161.BSART AS PurchasingDocumentType_BSART,
  t161.BSTYP AS PurchasingDocumentCategory_BSTYP,
  --   t161.BSAKZ AS ControlIndicatorForPurchasingDocumenType_BSAKZ,
  --   t161.PINCR AS ItemNumberInterval_PINCR,
  --   t161.NUMKI AS NumberRangeInTheCaseOfInternalNumberAssignment_NUMKI,
  --   t161.NUMKE AS NumberRangeInTheCaseOfExternalNumberAssignment_NUMKE,
  --   t161.BREFN As FieldSelectionKey_BREFN,
  --   t161.ABVOR AS PrepopulateStandardReleaseOrderQuantityinContract_ABVOR,
  --   t161.STAFO AS PrepopulateStandardReleaseOrderQuantityinContract_STAFO,
  --   t161.UPINC AS ItemNumberIntervalforSubitems_UPINC,
  --   t161.NUMKA AS NumberRangeinCaseofInternalNumberAssignmentforALE_NUMKA,
  --   t161.HITYP AS HierarchyCategoryVendorHierarchy_HITYP,
  --   t161.LPHIS AS IndicatorforScheduling_LPHIS,
  --   t161.GSFRG AS OverallReleaseofPurchaseRequisitions_GSFRG,
  --   t161.VARIANTE AS Layout_VARIANTE,
  --   t161.SHENQ AS OnlySharedLockinCaseofContractReleaseOrder_SHENQ,
  --   t161.KZALE AS DistributedContract_KZALE,
  --   t161.ABGEBOT AS CompetitiveBiddingProcedureUsingGlobalPercentageBids_ABGEBOT,
  --   t161.KORNR AS CorrectionofMiscellaneousProvisions_KORNR,
  --   t161.UMLIF AS StockTransfer_UMLIF,
  --   t161.KOETT AS ContractwithDeliverySchedule_KOETT,
  --   t161.AR_OBJECT AS DocumentType_AR_OBJECT,
  --   t161.KOAKO AS ContractAllowedasReleaseOrderAgainstContract_KOAKO,
  --   t161.OICSEGI AS QuantityScheduleCreationPermitted_OICSEGI,
  --   t161.OIRFQREQ AS PrecedenceforRFQorDefaultRequisitionforTDPPO_OIRFQREQ,
  --   t161.WVVKZ AS IndicatorforFurtherProcessingofSummarizedDocuments_WVVKZ,
  --   t161.XLOKZ AS CrossSystemTransit_XLOKZ,
  --   t161.CP_AKTIVE AS CommitmentPlanActive_CP_AKTIVE,
  --   t161.CPTYPE AS CategoryofCommitmentPlan_CPTYPE,
  --   t161.FLS_RSTO AS StoreReturnWithInboundandOutboundDelivery_FLS_RSTO,
  --   t161.MSR_ACTIVE AS AdvancedReturnsManagementActive_MSR_ACTIVE,
  --   t161.RDP_PROFILE AS RiskDistributionPlanProfile_RDP_PROFILE,
  --   t161.NUMKC AS NumberRangeforSRMCentralContract_NUMKC,
  --   t161.SAPMP_CEACT AS FastDataEntryofCharacteristicsIsActive_SAPMP_CEACT,
  --   t161.SAPMP_PPROT AS LogofCharacteristicValueInheritance_SAPMP_PPROT,
  --   t161.SAPMP_PUSER AS Inheritance_SAPMP_PUSER,
  --   t161.SAPMP_PAUSW AS InheritanceofCharacteristicsSelectionList_SAPMP_PAUSW,
  --   t161.SAPMP_ATNAM AS CharacteristicName_SAPMP_ATNAM,
  --   t161.SAPMP_GAUF AS GlobalLocalGroup_SAPMP_GAUF,
  --   t161.TOLSL AS ToleranceKey_TOLSL,
  --   t161.FSH_VAS_ACT AS  ActiveFlag_FSH_VAS_ACT,
  --   t161.FSH_VAS_KALSM AS DeterminationProcedure_FSH_VAS_KALSM,
  --   t161.FSH_VAS_DEL AS CriteriaforVASDeletion_FSH_VAS_DEL,
  --   t161.FSH_VAS_DETDT AS DateforVASDetermination_FSH_VAS_DETDT,
  --   t161.FSH_EXCL_RETURN AS ExcludeReturnItems_FSH_EXCL_RETURN,
  --   t161.FSH_VAR_KALSM AS DeterminationProcedure_FSH_VAR_KALSM,
  --   t161.FSH_DPR_DETPRO AS DeterminationProcedureforDistributionCurve_FSH_DPR_DETPRO,
  --   t161.FSH_PO_IDOC AS GenericArticleinPOUsingIDoc_FSH_PO_IDOC,
  --   t161.FSH_AUTO_DC AS AutomaticDistributionIndicator_FSH_AUTO_DC,
  --   t161.MILL_OMKZ AS ReferenceCharacteristicsInPurchasing_MILL_OMKZ,
  --   t161.WRF_ENABLE_DATELINE AS EnableDateline_WRF_ENABLE_DATELINE,
  t161t.BATXT AS PurchasingDocumentTypeText_BATXT,
  t161t.SPRAS AS Language_SPRAS
FROM
  `{{ project_id_src }}.{{ dataset_cdc_processed_ecc }}.t161` AS t161
INNER JOIN
  `{{ project_id_src }}.{{ dataset_cdc_processed_ecc }}.t161t` AS t161t
  ON
    t161.MANDT = t161t.MANDT
    AND t161.BSART = t161t.BSART
    AND t161.BSTYP = t161t.BSTYP
