#-- Copyright 2024 Google LLC
#--
#-- Licensed under the Apache License, Version 2.0 (the "License");
#-- you may not use this file except in compliance with the License.
#-- You may obtain a copy of the License at
#--
#--     https://www.apache.org/licenses/LICENSE-2.0
#--
#-- Unless required by applicable law or agreed to in writing, software
#-- distributed under the License is distributed on an "AS IS" BASIS,
#-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#-- See the License for the specific language governing permissions and
#-- limitations under the License.

-- ## EXPERIMENTAL

CREATE TABLE IF NOT EXISTS `{{ project_id_src }}.{{ k9_datasets_processing }}.dun_bradstreet_esg`
(
  duns BIGINT,
  country_iso_alpha_2_code STRING,
  organization_name STRING,
  major_industry_category STRING,
  industry_sector_category STRING,
  esg_ranking_score INT64,
  environmental_ranking_score INT64,
  environmental_ranking_score_reason_1 BIGINT,
  environmental_ranking_score_reason_2 BIGINT,
  environmental_ranking_score_reason_3 BIGINT,
  social_ranking_score INT64,
  social_ranking_score_reason_1 BIGINT,
  social_ranking_score_reason_2 BIGINT,
  social_ranking_score_reason_3 BIGINT,
  governance_ranking_score INT64,
  governance_ranking_score_reason_1 BIGINT,
  governance_ranking_score_reason_2 BIGINT,
  governance_ranking_score_reason_3 BIGINT,
  esg_ranking_peer_percentile STRING,
  environmental_ranking_peer_percentile STRING,
  social_ranking_peer_percentile STRING,
  governance_ranking_peer_percentile STRING,
  esg_ranking_average_peer_score DECIMAL(10, 2),
  environmental_ranking_average_peer_score DECIMAL(10, 2),
  social_ranking_average_peer_score DECIMAL(10, 2),
  governance_ranking_average_peer_score DECIMAL(10, 2),
  theme1_score INT64,
  theme2_score INT64,
  theme3_score INT64,
  theme4_score INT64,
  theme5_score INT64,
  theme6_score INT64,
  theme7_score INT64,
  theme8_score INT64,
  theme9_score INT64,
  theme10_score INT64,
  theme11_score INT64,
  theme12_score INT64,
  theme13_score INT64,
  theme14_score INT64,
  theme15_score INT64,
  theme16_score INT64,
  theme17_score INT64,
  theme18_score INT64,
  theme19_score INT64,
  theme20_score INT64,
  theme21_score INT64,
  theme22_score INT64,
  theme23_score INT64,
  theme24_score INT64,
  theme25_score INT64,
  theme26_score INT64,
  theme27_score INT64,
  theme28_score INT64,
  theme29_score INT64,
  theme30_score INT64,
  theme31_score INT64,
  theme32_score INT64,
  theme33_score INT64,
  theme34_score INT64,
  theme35_score INT64,
  theme36_score INT64,
  theme37_score INT64,
  theme38_score INT64,
  theme39_score INT64,
  theme40_score INT64,
  data_depth1 STRING,
  data_depth2 STRING,
  data_depth3 STRING,
  data_depth4 STRING,
  data_depth5 STRING,
  data_depth6 STRING,
  data_depth7 STRING,
  data_depth8 STRING,
  data_depth9 STRING,
  data_depth10 STRING,
  data_depth11 STRING,
  data_depth12 STRING,
  data_depth13 STRING,
  data_depth14 STRING,
  data_depth15 STRING,
  data_depth16 STRING,
  data_depth17 STRING,
  var1 STRING,
  var2 STRING,
  var3 STRING,
  var4 STRING,
  var5 STRING,
  var6 STRING,
  var7 STRING,
  var8 STRING,
  var9 STRING,
  var10 STRING,
  load_year INT64,
  load_month INT64,
  load_date INT64
);
